vich_uploader:
    db_driver: orm

    mappings:
       Images:
            uri_prefix: /img/user/chara
            upload_destination: '%kernel.project_dir%/public/img/user/chara'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
