vich_uploader:
    db_driver: orm

    mappings:
       products:
            uri_prefix: /img/user/chara
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
